version: "3"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
    restart: always
    volumes:
      - "../../epytodo.sql:/docker-entrypoint-initdb.d/epytodo.sql"
  myadmin:
    image: phpmyadmin
    ports:
      - "5001:80"
    links:
      - "db:db"
    restart: always